name: ActivateTracker
version: '${project.version}'
main: org.info_0.activatetracker.ActivateTracker
api-version: '1.20'
author: 'info_0'
commands:
  getreport:
    description: "Get report"
    usage: "/getreport"
permissions:
  activatetracker.ingametime:
    description: "If you have this permission, game tracking your in game time."
    default: op
