name: ActivateTracker
version: '${project.version}'
main: org.info_0.activatetracker.ActivateTracker
api-version: '1.20'
author: 'info_0'
commands:
  getreport:
    description: "Get report"
    usage: "/getreport"
    aliases: []
    permission: activate-tracker.getreport
permissions:
  activate-tracker.ingametime:
    description: "If you have this permission, game tracking your in game time."
    default: op
  activate-tracker.getreport:
    description: "If you have this permission, get reports."
    default: op
  activate-tracker.help:
    description: "Get wiki link"
    default: op